# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "3.5"

install: pip install -r requirements_test.txt

script: python runtests.py

notifications:
  email: false
